# application basic information...
server.port=9095
spring.application.name=easyticket
server.servlet.context-path=/easyticket

# DATABASE
# Postgresql DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket
spring.datasource.username=postgres
spring.datasource.password=ravan
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Set to false in production
logging.level.root=INFO
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


